### ISSUE TITLE
Work on web site design.

### ISSUE THREAD

**Issue by AloisReitbauer** [open-feature/open-feature.github.io#11]
We should work on a design for a cool look-and-feel for the website. Not that I don't like Oleg's HTML skills :-)

**Comment by oleg-nenashev** [comment]
> Not that I don't like Oleg's HTML skills :-)

There are none :) Just took the existing Hugo theme

**Comment by ThePeterDenham** [comment]
The "O" in the logo should be a toggle... what it toggles I do not know!

**Comment by beeme1mr** [comment]
@peterrattew, try clicking the toggle part of the logo found in the top left corner (desktop only) :smile:.
